# Generated by Django 3.0.7 on 2020-06-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_auto_20200613_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='ime',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='broj_naslova',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='kategorija',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='naslov',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='tekst',
        ),
    ]
