# Generated by Django 3.0.7 on 2020-06-15 12:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20200613_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vanjski_tekst',
            field=models.CharField(default='Klikite Link Iznad da Pročitate Post...', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
